# Generated by Django 4.1 on 2022-11-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_exam_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='avg_point',
            field=models.IntegerField(default=0),
        ),
    ]
