# Generated by Django 4.1 on 2022-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_subject_avg_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='kind',
            field=models.IntegerField(default=1),
        ),
    ]
