# Generated by Django 4.1 on 2022-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_subject_avg_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='avg_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
